settings:
  default_submit_button_label: L채het채
  default_reset_button_label: Palauta
  default_delete_button_label: Poista
  default_wizard_confirmation_label: Valmis
  default_preview_next_button_label: Esikatselu
  default_preview_label: Esikatselu
  dialog_options:
    normal:
      title: Normaali
element:
  default_more_title: Lis채채
