jobs:
  - job: InstallAndRun
    displayName: Run robot framework smoke tests - STAGE
    continueOnError: true
    pool:
      vmImage: 'windows-2019'
    strategy:
      matrix:
        Python37:
          python.version: "3.7"
      maxParallel: 1  

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"

      - script: pip install robotframework robotframework-pabot robotframework-seleniumlibrary webdrivermanager
        displayName: "Install dependencies"

      - powershell: robot --pythonpath . --variable environment:stage-chrome -x 'outputjunit.xml' '$(Build.SourcesDirectory)\test\tests\SMOKE-lomake-test-set.robot'
        failOnStderr: true
        displayName: "Run Robot Framework Tests"
        continueOnError: true

      #Publish test results after test run
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'outputjunit.xml'
          searchFolder: 'D:\a\1\s\logit\'
          publishRunAttachments: true
        condition: succeededOrFailed()
        displayName: 'Publish Test Results'

      #Copy test result files from agent machine to artifact staging directory
      - task: CopyFiles@2
        inputs:
          #SourceFolder: 'D:\a\1\s\'
          SourceFolder: $(System.DefaultWorkingDirectory)\logit\
          targetFolder: $(Build.ArtifactStagingDirectory)
        condition: succeededOrFailed()
        displayName: Copy test result files to artifact staging directory

      #Publish test results to BuildOutputs build artifact 
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: STAGE - Chrome
        condition: succeededOrFailed()
        displayName: Publish build artifacts