name: form_tool_config
description: 'Hel.fi Form Tool Config'
type: module
core_version_requirement: '^8.9 || ^9'
dependencies:
  - webform
  - webform_ui
  - webform_rest
  - helfi_base_config
version: '1.0.1'
package: HELfi
