ignored_config_entities:
  - 'eu_cookie_compliance.cookie_category*'
  - '*.site_settings'
  - 'webform.webform.*'
  - 'eu_cookie_compliance.cookie_category*'
  - hdbt_admin_tools.site_settings
_core:
  default_config_hash: QkouijUZWSmzRC1sUOJntoclIHqPYGTSt2534poifsQ
