user_never_lastlogin_value: ''
user_never_lastlogin_period: days
user_lastlogin_value: '5'
user_lastlogin_period: hours
user_inactive_value: ''
user_inactive_period: days
user_blocked_value: ''
user_blocked_period: days
enabled_never_loggedin_users: false
enabled_loggedin_users: true
enabled_inactive_users: false
enabled_blocked_users: false
purge_included_users_roles:
  helsinkiprofiili_heikko: helsinkiprofiili_heikko
  helsinkiprofiili_vahva: helsinkiprofiili_vahva
  authenticated: '0'
  read_only: '0'
  content_producer: '0'
  editor: '0'
  admin: '0'
  verkkolomake_kasittelija: '0'
  verkkolomake_hallinnoija: '0'
  verkkolomake_admin: '0'
  verkkolomake_kasittelija_todistus: '0'
  verkkolomake_kasittelija_testi123: '0'
  verkkolomake_kasittelija_sectest: '0'
purge_on_cron: true
inactive_user_notify_subject: 'Your account is deleted'
inactive_user_notify_text: "Dear User, \r\n\r\nYour account has been deleted due the website’s policy to automatically remove users who match certain criteria. If you have concerns regarding the deletion, please talk to the administrator of the website. \r\n\r\nThank you"
send_email_notification: false
purge_user_cancel_method: user_cancel_delete
disregard_blocked_users: false
purge_excluded_users_roles:
  admin: admin
  read_only: '0'
  content_producer: '0'
  editor: '0'
  helsinkiprofiili_heikko: '0'
  helsinkiprofiili_vahva: '0'
  verkkolomake_kasittelija: '0'
  verkkolomake_hallinnoija: '0'
  verkkolomake_admin: '0'
  verkkolomake_kasittelija_todistus: '0'
  verkkolomake_kasittelija_testi123: '0'
  verkkolomake_kasittelija_sectest: '0'
user_before_deletion_subject: 'Your account will be deleted'
user_before_deletion_text: "Dear User, \r\n\r\nYour account will be deleted soon due the website’s policy to automatically remove users who match certain criteria. If you have concerns regarding the deletion, please talk to the administrator of the website.  \r\n\r\nThank you"
send_email_user_before_notification: false
user_before_notification_value: ''
user_before_notification_period: days
