dialog_title: 'Sessionen håller på att gå ut'
yes_button: Fortsätta
no_button: 'Logga ut'
message: 'Din session håller på att gå ut. Vill du fortsätta?'
inactivity_message: 'Din session håller på att gå ut. Vill du fortsätta?'
