settings:
  default_form_close_message: 'Sorry&hellip; This form is closed to new submissions.'
  default_submit_button_label: Skicka
  default_reset_button_label: Återställ
  default_delete_button_label: Radera
  default_wizard_start_label: Från
  default_wizard_confirmation_label: Slutförd
  default_preview_next_button_label: Förhandsgranska
  default_preview_label: Förhandsgranska
  default_preview_message: 'Please review your submission. Your submission is not complete until you press the &quot;Submit&quot; button!'
  default_draft_button_label: 'Spara utkast'
  default_draft_saved_message: 'Formulär sparat. Du kan återvända till detta formulär senare och fortsätta inmatningen.'
  default_previous_submission_message: 'Du har redan skickat in detta formulär. <a href="#">Se ditt tidigare inlägg</a>.'
  dialog_options:
    narrow:
      title: Smal
    normal:
      title: Normal
    wide:
      title: Bred
element:
  default_more_title: Mer
  default_section_title_tag: h2
test:
  names: "first_name:\r\n  - 'John'\r\n  - 'Paul'\r\n  - 'Ringo'\r\n  - 'George'\r\nlast_name:\r\n  - 'Lennon'\r\n  - 'McCartney'\r\n  - 'Starr'\r\n  - 'Harrison'\r\naddress:\r\n  - '10 Main Street'\r\n  - '11 Brook Alley Road. APT 1'\r\nzip:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\npostal_code:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\nphone:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\nfax:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ncity:\r\n  - 'Springfield'\r\n  - 'Pleasantville'\r\n  - 'Hill Valley'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\ndefault:\r\n  - 'Loremipsum'\r\n  - 'Oratione'\r\n  - 'Dixisset'\r\n"
